### ISSUE TITLE
boost locale not included

### ISSUE THREAD

**Issue by patrickjwhite** [danoli3/ofxiOSBoost#15]
I see that locale is not one of the included boost libs, but can it be? I tried adding it to the BOOST_LIBS variable, but then I get an error in the output.

Thoughts? All the output seems squashed, so I can see what the real issue is yet.

**Comment by danoli3** [comment]
This may help:
```If iconv library is not found on Darwin/Mac OS X builds 
make sure there is no multiple iconv installations 
and provide -sICONV_PATH build option to point to correct location of iconv library.
```

``` Boost.Locale needs either iconv or ICU library to be built```

**Comment by danoli3** [comment]
You can also view the log on your disk after the failed build. 

I'm going to add a tail end of the log to console if error as well just for extra sense.

**Comment by singalen** [comment]
Voting for the pull request! I couldn't compile locale in `locale` without this.
