### ISSUE TITLE
boost iostreams support with zlib

### ISSUE THREAD

**Issue by jblough** [danoli3/ofxiOSBoost#16]
Thanks for the work you've gone on this!  I was attempting to add the boost iostreams library support by adding iostreams to the end of the BOOST_LIBS line in the sh scripts files.  Everything seems to compile fine and if I dump the library with "nm -g boost.a" the iostreams exports are listed in the library contents.  The problem is that the boost::iostreams::zlib functionality is missing which results in linker errors when attempting to link to the boost.a library from an app build.  This is more of a suggestion for ofxiOSBoost than an issue, but if iostreams with zlib support was built into the library then it might fix the issue if anyone else was having it as well.  Thanks!

**Comment by danoli3** [comment]
Hey @jblough, I believe zlib compiles into it's own lib file so that must be added into the lipo fat lib stage.

What formula did you add to the script to enable zlib for iostreams?

**Comment by jblough** [comment]
I just changed line 65 of the build-libc++.sh script to the following

`: ${BOOST_LIBS:="random regex graph random chrono thread signals filesystem system date_time iostreams"}`

It looks like all of the code lives in the header file "boost/iostreams/filter/zlib.hpp".

**Comment by jblough** [comment]
I’ve made a little progress on this by downloading the zlib source and pointing the environmental variable ZLIB_SOURCE to that directory before running the build-libc++.sh script.  At this point, the following error comes up for each of the .c source files in the zlib directory.

`...failed darwin.compile.c iphone-build/boost/bin.v2/standalone/zlib/darwin-8.1~iphone/release/architecture-arm/link-static/macosx-version-iphone-8.1/target-os-iphone/threading-multi/infback.o...
darwin.compile.c iphone-build/boost/bin.v2/standalone/zlib/darwin-8.1~iphone/release/architecture-arm/link-static/macosx-version-iphone-8.1/target-os-iphone/threading-multi/inffast.o
error: invalid argument '-std=c++11' not allowed with 'C/ObjC'`

`"/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++" "-arch" "armv7" "-arch" "arm64" "-fvisibility=hidden" "-fvisibility-inlines-hidden" "-DBOOST_AC_USE_PTHREADS" "-DBOOST_SP_USE_PTHREADS" "-std=c++11" "-stdlib=libc++" -x c -O3 -finline-functions -Wno-inline -Wall -gdwarf-2 -fexceptions -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk -pthread -arch arm  -DNDEBUG -D_LITTLE_ENDIAN  -I"/Users/me/zlib-1.2.8" -c -o "iphone-build/boost/bin.v2/standalone/zlib/darwin-8.1~iphone/release/architecture-arm/link-static/macosx-version-iphone-8.1/target-os-iphone/threading-multi/inffast.o" "/Users/me/zlib-1.2.8/inffast.c"`

Is it possible for the .c file extension to be recognized as different from the boost .cpp files and use different compiler flags?  Would that be part of the ofxiOSBoost build scripts or the boost build scripts that download with the boost library tarball?  Thanks!

**Comment by danoli3** [comment]
Nice yeah that is how you would do it.
I can add a ```zlib``` tar ball download, if it detects ```iostreams``` in the BOOST_LIBS and  automatically add it to the linker.

With the passing of the std=c++11, this was assuming that BOOST is 100% C++, so bjam is sending the CPP compiler flags to all files. I know in makefiles you can easily swap this for .c and .cpp to different compiler flags. So I'll have to have a look inside the bjam process see if possible.

Else: Try and remove the ```-std=$CPPSTD``` from the ```EXTRA_CPPFLAGS``` and see what happens for now. Setting the c++ standard may not be actually necessary anyway since most of the libc++/c++11 work is covered by ```-stdlib=``` flag.

**Comment by jblough** [comment]
To get it to successfully compile into the boost.a file, I needed to remove the -std and -stdlib flags from EXTRA_CPPFLAGS and also run configure and make from within the zlib source directory before running the build-libc++.sh script.  The zlib source files couldn't find their headers until configure and make was run.  Thanks for all your help!
