### ISSUE TITLE
Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by bapzangbo** [danoli3/ofxiOSBoost#19]
Sorry my bad English, i newer in ios programing. Im try using your boost lib in this http://stackoverflow.com/questions/17532252/boost-libraries-into-ios-project
but when build, i have the problem

No member named 'addressof' in namespace std

no member named 'weak_ptr' in namespace 'std': did you mean "boost::weak_ptr"

**Comment by danoli3** [comment]
Make sure you are targeting the correct release within Xcode.

If you have libc++ release (or master branch), make sure your project has the compiler set to libc++
Alternatively: if you have the libstdc++ release (Another release in the release section https://github.com/danoli3/ofxiOSBoost/releases), make sure the project is then set to libstdc++

Double check those. If it's still an issue it may be a problem I'll have to fix.

**Comment by bapzangbo** [comment]
Thanks for your support, i have fix problem with your solution 
^_^

**Comment by danoli3** [comment]
Awesome!

**Comment by bapzangbo** [comment]
OMG, im still have problem
im using your libstdc++ release  and change C++ Language Dialect to C++11[-std=c++11]
and C++ Standard Library to libstdc++ (GNU C++ standard library), everything is ok in this morning. But,after a little time later. im include boost/asio with BOOST_ASIO_DYN_LINK and BOOST_ASIO_SEPARATE_COMPLIATION in preprocessing at both Debug and Relase mode, i have same problem that post above
