### ISSUE TITLE
Cannot build libtorrent with your boost

### ISSUE THREAD

**Issue by bapzangbo** [danoli3/ofxiOSBoost#20]
im trying build libtorrent-rasterbar using 
./configure --prefix=/Myfolder --with-openssl=/FolderOpensslBuilded --with-boost=/ofxiOSBoost-1.58.0-libc- --with-boost-libdir=/ofxiOSBoost-1.58.0-libc-/lib

and i have a problem
Checking for boost libraries:
checking for boostlib >= 1.36... yes
checking whether the Boost::System library is available... yes
configure: error: Boost.System library not found. Try using --with-boost-system=lib

seem to be missing lboost_system, how can i fix this problem

**Comment by danoli3** [comment]
Try and add ```--with-boost-system=ofxiOSBoost-1.58.0-libc-/libs/boost/ios/boost.a" <-- just modify this to the position of the boost.a file.

The build process creates a "FAT" static library that contains the boost_system.a. So if you manually specify all required libs to that single static lib file (boost.a) it should link correctly.

**Comment by bapzangbo** [comment]
Finally, with your help, i cant build the libtorrent. by the way, i have an outside question. when build success libtorrent with your boost. im using simple client of libtorrent.
code in main.mm like that
 #import <UIKit/UIKit.h>
#import "AppDelegate.h"
#import <boost/asio.hpp>
#import <boost/filesystem.hpp>
#import <libtorrent/torrent_handle.hpp>
#import <libtorrent/session.hpp>
#import <libtorrent/entry.hpp>
#import <libtorrent/bencode.hpp>
#import <string>
#import <stdlib.h>

using namespace std;
using namespace boost::filesystem;
using namespace boost;


int main(int argc, char * argv[]) {
    @autoreleasepool {
        NSLog(@"WELCOME TO MY SIM");        
        NSString *documentsDirectory = [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) objectAtIndex:0];
        string *path_save=new string([documentsDirectory UTF8String]);                       
        NSLog(@"PATH SAVE= %s",path_save->c_str());        
        path p; {            
            path_save->c_str();
        };        
        long long fre=0;
        long long avai=0;
        long long cap=0;
        
        try {
            space_info s=space(p);
            fre=s.free;
            avai=s.available;
            cap=s.capacity;
        } catch (filesystem_error &e) {
            NSLog(@"ERROR %s",e.what());
        } 
        NSLog(@"TOTAL FREE: %llu",fre);
        NSLog(@"TOTAL AVAILABLE: %llu",avai);
        NSLog(@"TOTAL CAPACITY: %llu",cap);
       
        /*START DOWNLOAD*/
        NSLog(@"START DOWNLOAD TORRENT");
        
        libtorrent::session s;
  return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));
    }
}

when build with xcode 6. i have error
im search thousand in google, cut cannot find any solution to fix that. 

Undefined symbols for architecture i386:
  "libtorrent::absolutetime_deprecated_()", referenced from:
      libtorrent::session::session(libtorrent::fingerprint const&, int, unsigned int) in main.o
  "libtorrent::session::init(std::pair<int, int>, char const*, libtorrent::fingerprint const&, unsigned int)", referenced from:
      libtorrent::session::session(libtorrent::fingerprint const&, int, unsigned int) in main.o
  "libtorrent::session::start(int)", referenced from:
      libtorrent::session::session(libtorrent::fingerprint const&, int, unsigned int) in main.o
  "libtorrent::session::~session()", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

THANK for your help and your attention

**Comment by danoli3** [comment]
Not sure @bapzangbo, looks like something broken with the lib torrent library you are trying to build.

Missing symbols could mean that code referenced in the headers no longer exists in the static binary for lib torrent. (version disparity or just broken lib). Try and checkout the latest lib torrent or report the issue on their repo.
