### ISSUE TITLE
linker errors when building for simulator in Xcode 7

### ISSUE THREAD

**Issue by gereons** [danoli3/ofxiOSBoost#23]
I just updated to Xcode 7, and when I build for any simulator, I'm gettings this error message:

ld: in ....../libtracker.a(c_regex_traits.o), building for iOS simulator, but linking in object file built for OSX, for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any idea what could be causing this?

**Comment by gereons** [comment]
In addition, I'm now also seeing this warning 

ld: warning: direct access in boost::exception_ptr boost::exception_detail::get_static_exception_object<boost::exception_detail::bad_alloc_>() to global weak symbol guard variable for boost::exception_ptr boost::exception_detail::get_static_exception_object<boost::exception_detail::bad_alloc_>()::ep means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.

(about 30 of them) after cleaning up some other warnings.

**Comment by danoli3** [comment]
Thanks I'll make sure to fix this with the next iOSboost version for 1.59.0

Seems clang is more particular about some symbols that don't exist by boosts exclusion.

I fixed a similar issue before by hard coding a excluded header from boost, however fingers crossed it is fixed in 1.59

**Comment by gereons** [comment]
Thanks! Do you have a time estimate for this update? Not being able to build for the simulators is quite annoying...

**Comment by danoli3** [comment]
According to Apple: 
> In Xcode 7, the linker enforces that all files linked together were built for the same platform. You control the platform via -mmacosx-version-min=XX or -miphoneos-version-min=XX

Source:
http://karp.id.au/post/xcode_7_linker_rules/

Should be an easy fix then

**Comment by danoli3** [comment]
Two new releases with 1.59.0 fix this problem.
Build script has been updated as well.
Master is now working with Xcode 7

**Comment by gereons** [comment]
Thanks! Linker problems are fixed. I'm still getting a bunch of those direct access warnings that I don't understand, but at least I can use the Simulator again.

**Comment by danoli3** [comment]
:+1:
