### ISSUE TITLE
boost.a needs to be libboost.a for Cocoapods

### ISSUE THREAD

**Issue by mhaylock** [danoli3/ofxiOSBoost#26]
Trying to use the Cocoapod for this project it _almost_ works out of the box, except that the linker can't find boost. I found the fix to be renaming `boost.a` to `libboost.a`.

My fix for the moment is to add this to the projects `Podfile`:
```ruby
post_install do |installer|
    # ofxiOSBoost has the boost library named 'boost.a', but it needs to be
    # called 'libboost.a' for the linker to find it, we will rename it here:
    boost_root_path = installer.sandbox.pod_dir('ofxiOSBoost')
    boost_lib_path = boost_root_path.join('libs/boost/ios/boost.a')
    boost_lib_path.rename(boost_lib_path.parent.join 'libboost.a') if boost_lib_path.exist?
end
```

But if some fix could be made upstream here that would be great.

**Comment by danoli3** [comment]
Yeah thanks for this report!
I think I will go with the name change.

I have got into the habit of renaming libs and to not conflict with system libs, however this should have priority so I think it should be a go.

Thanks again! I'll make the adjustments

**Comment by danoli3** [comment]
Changed to libboost.a in new releases for 1.59.0 and master.
