### ISSUE TITLE
Any support for Boost Extensions?

### ISSUE THREAD

**Issue by tetriscode** [danoli3/ofxiOSBoost#32]
I'm currently using ofxiOSBoost but would like to use the boost [geometry extensions](https://github.com/boostorg/geometry/tree/develop/include/boost/geometry/extensions). Is there any simple way to do this without forking and doing by hand?

**Comment by danoli3** [comment]
Hey @tetriscode, with the provided build script in the "scripts/build-libc++"

Just edit with a text editor, such as Sublime Text or Text Editor and change the following line:
https://github.com/danoli3/ofxiOSBoost/blob/master/scripts/build-libc%2B%2B#L68

To include geometry
```
: ${BOOST_LIBS:="random regex graph random chrono thread signals filesystem system date_time geometry"}
```

I might add this as a default for the next Boost Release though

**Comment by tetriscode** [comment]
Thanks
